int a = 2;
int b = 5;
int c = 3;
int d = 10;
int e = 12;
int max = a;
if (b > max) max = b;
if (c > max) max = c;
if (d > max) max = d;
if (e > max) max = e;
Console.Write("Максимум равен: ");
Console.WriteLine(max);